---
application:
  name: "dtc-fundraiser"
  project: "DTC-FundRaiser"
  organization: "QoveryCommunity"
routers:
- name: "main-dtc-fundraiser"
  routes:
  - application_name: "dtc-fundraiser"
    paths:
    - "/*"
